package tech.vvp.vvp.client.model;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity;
import net.minecraft.util.Mth;
import tech.vvp.vvp.entity.vehicle.Leopard2A4Entity;

public class Leopard2A4Model extends VehicleModel<Leopard2A4Entity> {

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return true;
    }

    // Generated by Track Builder - 71 tracks
// Generated by Track Builder - 55 tracks
// Pivot: [0, 22.50, 67.75]

    private static final int TRACK_COUNT = 55;
    private static final int MAX_IDX = 55;
    private static final float[][] KEYFRAMES = {
            {176.79f, 22.50f, 67.75f},
            {133.14f, 20.51f, 72.21f},
            {83.82f, 15.86f, 73.71f},
            {36.97f, 11.64f, 71.26f},
            {39.45f, 8.47f, 67.35f},
            {39.45f, 5.27f, 63.46f},
            {39.45f, 2.07f, 59.58f},
            {0.57f, 0.50f, 54.92f},
            {0.00f, 0.50f, 49.89f},
            {0.00f, 0.50f, 44.86f},
            {0.00f, 0.50f, 39.83f},
            {0.00f, 0.50f, 34.79f},
            {0.00f, 0.50f, 29.76f},
            {0.00f, 0.50f, 24.73f},
            {0.00f, 0.50f, 19.70f},
            {0.00f, 0.50f, 14.66f},
            {0.00f, 0.50f, 9.63f},
            {0.00f, 0.50f, 4.60f},
            {0.00f, 0.50f, -0.44f},
            {0.00f, 0.50f, -5.47f},
            {0.00f, 0.50f, -10.50f},
            {0.00f, 0.50f, -15.53f},
            {0.00f, 0.50f, -20.57f},
            {0.00f, 0.50f, -25.60f},
            {0.00f, 0.50f, -30.63f},
            {-22.29f, 1.10f, -35.58f},
            {-35.92f, 3.95f, -39.72f},
            {-35.92f, 6.91f, -43.79f},
            {-35.92f, 9.86f, -47.87f},
            {-36.99f, 12.79f, -51.96f},
            {-85.47f, 17.11f, -54.23f},
            {-133.95f, 21.69f, -52.54f},
            {-179.76f, 23.50f, -48.00f},
            {179.51f, 23.45f, -42.96f},
            {179.51f, 23.41f, -37.93f},
            {179.51f, 23.37f, -32.90f},
            {179.51f, 23.32f, -27.87f},
            {179.51f, 23.28f, -22.83f},
            {179.51f, 23.24f, -17.80f},
            {179.51f, 23.19f, -12.77f},
            {179.51f, 23.15f, -7.74f},
            {179.51f, 23.11f, -2.70f},
            {179.51f, 23.06f, 2.33f},
            {179.51f, 23.02f, 7.36f},
            {179.51f, 22.98f, 12.39f},
            {179.51f, 22.93f, 17.43f},
            {179.51f, 22.89f, 22.46f},
            {179.51f, 22.85f, 27.49f},
            {179.51f, 22.80f, 32.52f},
            {179.51f, 22.76f, 37.56f},
            {179.51f, 22.72f, 42.59f},
            {179.51f, 22.67f, 47.62f},
            {179.51f, 22.63f, 52.65f},
            {179.51f, 22.59f, 57.69f},
            {179.51f, 22.54f, 62.72f},
            {176.79f, 22.50f, 67.75f}
    };

    private static final float START_Y = 22.50f;
    private static final float START_Z = 67.75f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

    @Override
    public int getDefaultWrapRange(VehicleEntity vehicle) {
        return TRACK_COUNT * 2;
    }
}
