package tech.vvp.vvp.client.model;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity;
import net.minecraft.util.Mth;
import tech.vvp.vvp.entity.vehicle.PumaEntity;

public class PumaModel extends VehicleModel<PumaEntity> {

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return true;
    }

    // Generated by Track Builder - 61 tracks
// Pivot: [0, 22.52, 52.45]

    private static final int TRACK_COUNT = 61;
    private static final int MAX_IDX = 61;
    private static final float[][] KEYFRAMES = {
            {176.89f, 22.52f, 52.45f},
            {138.80f, 21.19f, 56.14f},
            {100.02f, 17.82f, 58.14f},
            {61.24f, 13.95f, 57.54f},
            {39.42f, 11.13f, 54.75f},
            {39.42f, 8.59f, 51.66f},
            {39.42f, 6.05f, 48.57f},
            {39.42f, 3.51f, 45.48f},
            {7.41f, 1.96f, 41.87f},
            {0.00f, 1.93f, 37.87f},
            {0.00f, 1.93f, 33.87f},
            {0.00f, 1.93f, 29.87f},
            {0.00f, 1.93f, 25.87f},
            {0.00f, 1.93f, 21.87f},
            {0.00f, 1.93f, 17.87f},
            {0.00f, 1.93f, 13.87f},
            {0.00f, 1.93f, 9.87f},
            {0.00f, 1.93f, 5.86f},
            {0.00f, 1.93f, 1.86f},
            {0.00f, 1.93f, -2.14f},
            {0.00f, 1.93f, -6.14f},
            {0.00f, 1.93f, -10.14f},
            {0.00f, 1.93f, -14.14f},
            {0.00f, 1.93f, -18.14f},
            {0.00f, 1.93f, -22.14f},
            {0.00f, 1.93f, -26.14f},
            {0.00f, 1.93f, -30.14f},
            {-7.15f, 2.02f, -34.13f},
            {-32.43f, 3.71f, -37.72f},
            {-32.43f, 5.85f, -41.10f},
            {-32.43f, 8.00f, -44.47f},
            {-32.43f, 10.14f, -47.85f},
            {-32.61f, 12.29f, -51.23f},
            {-70.12f, 15.27f, -53.77f},
            {-109.19f, 19.19f, -53.84f},
            {-148.26f, 22.25f, -51.40f},
            {-178.23f, 23.10f, -47.56f},
            {179.76f, 23.09f, -43.56f},
            {179.66f, 23.07f, -39.56f},
            {179.66f, 23.05f, -35.56f},
            {179.66f, 23.02f, -31.56f},
            {179.66f, 23.00f, -27.56f},
            {179.66f, 22.97f, -23.56f},
            {179.66f, 22.95f, -19.56f},
            {179.66f, 22.93f, -15.56f},
            {179.66f, 22.90f, -11.56f},
            {179.66f, 22.88f, -7.56f},
            {179.66f, 22.86f, -3.56f},
            {179.66f, 22.83f, 0.44f},
            {179.66f, 22.81f, 4.44f},
            {179.66f, 22.78f, 8.44f},
            {179.66f, 22.76f, 12.44f},
            {179.66f, 22.74f, 16.45f},
            {179.66f, 22.71f, 20.45f},
            {179.66f, 22.69f, 24.45f},
            {179.66f, 22.66f, 28.45f},
            {179.66f, 22.64f, 32.45f},
            {179.66f, 22.62f, 36.45f},
            {179.66f, 22.59f, 40.45f},
            {179.66f, 22.57f, 44.45f},
            {179.66f, 22.55f, 48.45f},
            {176.89f, 22.52f, 52.45f}
    };

    private static final float START_Y = 22.52f;
    private static final float START_Z = 52.45f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

    @Override
    public int getDefaultWrapRange(VehicleEntity vehicle) {
        return TRACK_COUNT * 2;
    }
}
